#! /usr/bin/ruby

require 'rubygems'
require 'kramtex.rb'

TEX_CRAP = [".aux", ".log", ".out", ".tex", ".pdf"]

filename = ARGV.first
abort("Can't find the .markdown file") unless File.exist?("#{filename}.markdown")

TEX_CRAP.each { |ext| File.delete(filename+ext) if File.exist?(filename+ext)}

kramtex = KramTeX::Document.new(filename)
file = kramtex.open_file
kramtex.convert_to_document( file ) do |document|
  kramtex.write_output( document )
  system( "xelatex #{filename}.tex" )
  system( "open #{filename}.pdf" ) if File.exist?("#{filename}.pdf")
end

